name: redstone_cookies_plugin
version: 0.0.1
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: Redstone plugin to get DI of the cookies header field
homepage: https://github.com/redstone-dart/redstone_cookies_plugin
environment:
  sdk: '>=1.9.1'
documentation: https://github.com/redstone-dart/redstone_cookies_plugin
dependencies:
  redstone: '>=0.6.0-beta.1 < 0.7.0'
  cookies: ">=0.0.3 < 1.0.0"
